### ISSUE TITLE
Can't find device

### ISSUE THREAD

**Issue by JBergsee** [testableapple/xcmonkey#23]
Hi!

Nice tool, just what I need!

Unfortunately I can't get it to work. Trying UDIDs from the XCode "Devices and simulators" window, the only feedback I get from xcmonkey is ` Can't find device 62291923-EE3D-40AF-B1B2-C99831BA6142`. 
The app I want to stress test is running on the simulator with the given UDID. What am I doing wrong?

**Comment by testableapple** [comment]
Hi @JBergsee,
Thanks for reporting this!

The tool uses this command to fetch all simulators: `idb list-targets --json` 
Could you please run it locally and share the output.

Best wishes,
Alexey

**Comment by JBergsee** [comment]
Hi,

Thank you, it lists my AppleDisplay and my connected iPad, but not any of the simulators in XCode. Why aren't they recognized?

**Comment by testableapple** [comment]
@JBergsee, could you please share output of these commands:
- `xcode-select -p`
- `gcc --version`

And confirm if `xcrun simctl list` does show your `iOS Simulators`?

**Comment by JBergsee** [comment]
Thank you for helping!

Here's the output:
```
johan@MBP-M2-Max ~ % xcode-select -p
/Library/Developer/CommandLineTools
johan@MBP-M2-Max ~ % gcc --version  
Apple clang version 14.0.3 (clang-1403.0.22.14.1)
Target: arm64-apple-darwin22.4.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
johan@MBP-M2-Max ~ % xcrun simctl list
xcrun: error: unable to find utility "simctl", not a developer tool or in PATH
johan@MBP-M2-Max ~ % echo $PATH
/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin
johan@MBP-M2-Max ~ % export PATH=$PATH:/Library/Developer/CommandLineTools/usr/bin
johan@MBP-M2-Max ~ % echo $PATH
/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/Library/Developer/CommandLineTools/usr/bin
johan@MBP-M2-Max ~ % xcrun simctl list
xcrun: error: unable to find utility "simctl", not a developer tool or in PATH
```

**Comment by testableapple** [comment]
Awesome, I'm glad it is fixed now for you!
And I hope you'll enjoy playing with `xcmonkey` 🙂
