### ISSUE TITLE
Is there any roadmap that support real device?

### ISSUE THREAD

**Issue by antstudio-git** [testableapple/xcmonkey#32]
As the title

**Comment by testableapple** [comment]
Hi @antstudio-git,
Beg your pardon, I somehow missed this ticket.

`xcmonkey` depends on `idb`, which is, unfortunately, limited to iOS Simulators in terms of accessibility automation. At least at the moment. See this [documentation](https://fbidb.io/docs/accessibility) for more details. Hope this helps.

Best wishes,
Alexey
